-- Selects productions that are less than 50% full.
SELECT
  PRODUCTION_NO,
  COUNT(*),
  SUM(PERFORMANCE_SEATS)                           AS SEAT_COUNT,
  COUNT(*) * 20                                    AS MAX_SEATS,
  (SUM(PERFORMANCE_SEATS) * 100) / (COUNT(*) * 20) AS PCNT_FULL
FROM
  PERFORMANCES
GROUP BY PRODUCTION_NO
HAVING
  ((SUM(PERFORMANCE_SEATS) * 100) / (COUNT(*) * 20)) < 50;


SELECT
  ID,
  PRODUCTION_TITLE
FROM PRODUCTIONS
WHERE ID IN (
  SELECT
    PRODUCTION_NO
    --,(SUM(PERFORMANCE_SEATS) * 100) / (COUNT(*) * 20) AS PCNT_FULL
  FROM
    PERFORMANCES
  GROUP BY PRODUCTION_NO
  HAVING
    ((SUM(PERFORMANCE_SEATS) * 100) / (COUNT(*) * 20)) < 50);
